fastnlo.rb, lhapdf.rb, rivet.rb, sherpa.rb
This introduces several Sherpa-related changes.
* Fix dependencies compilation on linux
* MPI and root options
* Fix another iterator-related segfault on OSX
* FastNLO 2.3 (I know the current version is called pre-release, but it works quiet well)
=> various changes

pythia8.rb
The VINCIA plugin may need to be updated...
=> Update Pythia to v8.215

Formula/herwig.rb
* Fixes `brew audit`
* Fixes PDF download from within install stanza
* But test currently doesn't pass
=> herwig: fix audit

Formula/hepmc3.rb
Update HepMC3 formula
- [+] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [+] Built your formula locally prior to submission with `brew install <formula>`?
- [+] Checked that the tests still pass?
=> hepmc3:  3.1.2

Formula/pythia.rb, Formula/vincia.rb
=> Pythia -> 8243 vincia -> 2.3.01

Formula/hepmc3.rb
=> Update HepMC3 to 3.2.2

Formula/apfelxx.rb, Formula/elementary-utils.rb, Formula/numa.rb, Formula/partons.rb, README.md
Unfortunately, it is hard to build a test program inside PARTONS. Is that really strictly required?
=> PARTONS along its dependencies

Formula/applgrid.rb, Formula/hoppet.rb
=> update Hoppet to v1.2

Formula/hepmc.rb
=> update to HepMC-2.06.11 with weights ordering bugfix

Formula/f2c.rb, Formula/fastjet.rb, Formula/herwig.rb, Formula/lhapdf.rb, Formula/madgraph5_amcatnlo.rb, Formula/mcfm.rb, Formula/mcgrid.rb, Formula/openloops.rb, Formula/partons.rb, Formula/rivet.rb, Formula/sherpa.rb, Formula/thepeg.rb, Formula/yoda.rb
=> style fixed

Formula/hepmc3.rb
=> HepMC3 3.2.5

.github/workflows/publish.yml, .github/workflows/tests.yml, Formula/binder.rb, Formula/f2c.rb, Formula/partons.rb, Formula/sherpa.rb
1. `brew test-bot` action builds bottles and uploads as artifacts to GitHub Packages. This runs on each commit in the PR.
2. `brew pr-pull` action commits bottle hash to formula. This runs once when the PR is labeled as ready to merge.
**Important:** This changes the workflow for merging a PR into homebrew-hep. When a PR has changed a formula in a way that requires a new bottle, instead of clicking the "Merge" button you should now add the `pr-pull` label. This will trigger the second GitHub Action, which will eventually close the PR. [Homebrew blog post.](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/)
FYI @ebothmann @cjohnson-phys
=> GitHub Actions for bottles

Formula/yoda.rb, audit_exceptions/flat_namespace_allowlist.json
=> yoda 1.9.4

Formula/fastjet.rb
=> fastjet 3.4.0

Formula/hepmc2.rb
Hi @davidchall ,
this is the old HepMC formula added back.
Best regards,
Andrii
=> Added back HepMC v2 as HepMC2

Formula/hepmc.rb, Formula/hepmc3.rb, Formula/herwig.rb, Formula/pythia.rb, Formula/rivet.rb, Formula/sherpa.rb, Formula/thepeg.rb, Formula/whizard.rb, formula_renames.json
The end result of #209, #210 and #211 is that we have 2 formulae: `hepmc2` and `hepmc3`.
=> Revert hepmc -> hepmc3; Rename original hepmc -> hepmc2

Aliases/amcatnlo, Aliases/madgraph5
madgraph5 -> madgraph5_amcatnlo
amcatnlo -> madgraph5_amcatnlo
=> Add aliases

Formula/fastjet.rb
Also fix audit complaint about url
Doesn't impact installation, so we don't need to bump revision.
=> fastjet: fix test

Formula/lhapdf.rb
Reverts davidchall/homebrew-hep#262
=> Revert "lhapdf: 6.5.3"

Formula/hepmc3.rb, Formula/rivet.rb, Formula/sherpa.rb
- [ x ] Checked that the tests still pass?
=> Update HepMC3 to 3.2.6
